### ISSUE TITLE
Mixins in development environment

### ISSUE THREAD

**Issue by mchorse** [mouse0w0/forge-mixin-example#1]
Hello, I think it's worth adding following to the `minecraft {}` section of `build.gradle`:

```groovy
String resolved_core_config = mod_mixin_configs.replace('${mod_id}', mod_id);
clientRunArgs += "--mixin ${resolved_core_config}"
serverRunArgs += "--mixin ${resolved_core_config}"
```

As of right now, Mixins don't work in development environment without providing the JSON file explicitly.

**Comment by mouse0w0** [comment]
This repository is just to show an example of using Mixin in Forge. You could modify it according to your needs.

I have no idea how to fix it. Welcome to submit pull request.

**Comment by mchorse** [comment]
Alright, I’ll do in a bit! Thank you for example though!
