### ISSUE TITLE
gradlew is not executable

### ISSUE THREAD

**Issue by anatawa12** [mouse0w0/forge-mixin-example#12]
could you add the executable flag to make it easy to develop from POSIX-like platforms.

**Comment by mouse0w0** [comment]
gradlew is provided by Gradle. What's wrong with it? Please describe your problem clearly.

**Comment by anatawa12** [comment]
The executable flag in posix file mode of gradlew file is not sey. Please set executable flag.

**What's executable flag? What's posix file mode?**

Posix-like systems has simple permission system. The permission system has 3 flags for 3 tagets, in total 9 flags. We may call the flags as 'file mode'. The 3 flags are readable, writable, and executable. If executable flag is not set, we can't run execute a file as a command.

In the MS-DOS and Windows, there's no such a permission system so you can run 'gradlew' to run 'gradlew.bat' so git on windows often drops the flag.

**Why posix flag is relates to the repository?**

The Git controls the posix file mode.

**How to add executable flag**

If your OS is posix (like linux, macos, \*BSD), `chmod +x gradlew` to add executable flag and git add&commit. 
If your os is not posix (like MS-DOS family like windows), `git update-index --chmod=+x gradlew` to add executable flag on git index tree and commit.

**Comment by mouse0w0** [comment]
OK, I get it. Thank you for your contribution.
