### ISSUE TITLE
Could not find mixingradle.jar (org.spongepowered:mixingradle:0.7-SNAPSHOT).

### ISSUE THREAD

**Issue by 12345-mcpython** [mouse0w0/forge-mixin-example#16]
Platform: Windows
Log:
PS E:\code\java\delete-silverfish> .\gradlew

Welcome to Gradle 4.10.3!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.3/release-notes.html

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.10.3/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'delete-silverfish'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find mixingradle.jar (org.spongepowered:mixingradle:0.7-SNAPSHOT).
     Searched in the following locations:
         https://files.minecraftforge.net/maven/org/spongepowered/mixingradle/0.7-SNAPSHOT/mixingradle-0.7-SNAPSHOT.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by mouse0w0** [comment]
Please check your network config, use proxy in Gradle.

**Comment by 12345-mcpython** [comment]
It isn't the network problem. When I opened https://maven.minecraftforge.net/org/spongepowered/mixingradle/0.7-SNAPSHOT/mixingradle-0.7-SNAPSHOT.jar, it returned 404.

**Comment by mouse0w0** [comment]
Reorder repositories and try again.
```gradle
buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/maven' } // Move it before forge repository.
        maven { url = 'https://files.minecraftforge.net/maven' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}
```

**Comment by 12345-mcpython** [comment]
OK. It work.
