### ISSUE TITLE
Any plans on supporting the last forge version on 1.12?

### ISSUE THREAD

**Issue by ghost** [mouse0w0/forge-mixin-example#3]

**Comment by mouse0w0** [comment]
OK, I’ll do it. As a temporary solution, you can modify `forge_version` and `mapping_version` in `gradle.properties` for supporting any forge version.

**Comment by ghost** [comment]
Ok, thanks a lot

**Comment by mouse0w0** [comment]
I have supported ForgeGradle 3.+, it can support the latest forge version (As for now, it is `14.23.5.2855`). For stability, the forge version of template is the latest **recommended** (`14.23.5.2854`). If you want to use higher version, you can modify `forge_version` just like before. 

Now the template of supporting ForgeGradle 2.3 has been moved to `14.23.5.2847` branch.
